import DraggableElement from "@src/structures/DraggableElement";
import Vector2 from "@src/structures/Vector2";
import {PuzzleLayersEnum} from "@src/helpers/PuzzleConstants";

export default [
    new DraggableElement({
        name: 'item1',
        size: new Vector2(247, 179),
        initialPosition: new Vector2(830, 770),
        targetPosition: new Vector2(337, 422),
        layer: PuzzleLayersEnum.LAYER1,
        finalLayer: PuzzleLayersEnum.LAYER1,
        image: 'Galva.png',
    }),
    new DraggableElement({
        name: 'item2',
        size: new Vector2(967, 298),
        initialPosition: new Vector2(10, 720),
        targetPosition: new Vector2(472, 366),
        layer: PuzzleLayersEnum.LAYER1,
        finalLayer: PuzzleLayersEnum.LAYER0,
        image: 'Veders.png',
    }),
    new DraggableElement({
        name: 'item3',
        size: new Vector2(216, 190),
        initialPosition: new Vector2(1470, 758),
        targetPosition: new Vector2(1366, 401),
        layer: PuzzleLayersEnum.LAYER1,
        finalLayer: PuzzleLayersEnum.LAYER1,
        image: 'Aste.png',
    }),
    new DraggableElement({
        name: 'item4',
        size: new Vector2(188, 90),
        initialPosition: new Vector2(710, 744),
        targetPosition: new Vector2(1170, 548),
        layer: PuzzleLayersEnum.LAYER2,
        finalLayer: PuzzleLayersEnum.LAYER2,
        image: 'Apaksa_Tresa_Spura.png',
    }),
    new DraggableElement({
        name: 'item5',
        size: new Vector2(55, 54),
        initialPosition: new Vector2(642, 912),
        targetPosition: new Vector2(422, 465),
        layer: PuzzleLayersEnum.LAYER2,
        finalLayer: PuzzleLayersEnum.LAYER2,
        image: 'Acs.png',
    }),
    new DraggableElement({
        name: 'item6',
        size: new Vector2(198, 82),
        initialPosition: new Vector2(700, 906),
        targetPosition: new Vector2(689, 294),
        layer: PuzzleLayersEnum.LAYER2,
        finalLayer: PuzzleLayersEnum.LAYER2,
        image: 'Augsa_Pirma_Spura.png',
    }),
    new DraggableElement({
        name: 'item7',
        size: new Vector2(211, 104),
        initialPosition: new Vector2(1017, 895),
        targetPosition: new Vector2(961, 611),
        layer: PuzzleLayersEnum.LAYER2,
        finalLayer: PuzzleLayersEnum.LAYER2,
        image: 'Apaksa_Videja_Spura.png',
    }),
    new DraggableElement({
        name: 'item8',
        size: new Vector2(146, 85),
        initialPosition: new Vector2(1073, 746),
        targetPosition: new Vector2(652, 497),
        layer: PuzzleLayersEnum.LAYER2,
        finalLayer: PuzzleLayersEnum.LAYER2,
        image: 'Videja_Spura.png',
    }),
    new DraggableElement({
        name: 'item9',
        size: new Vector2(165, 126),
        initialPosition: new Vector2(1181, 843),
        targetPosition: new Vector2(581, 623),
        layer: PuzzleLayersEnum.LAYER2,
        finalLayer: PuzzleLayersEnum.LAYER2,
        image: 'Apakseja_Pirma_Spura_.png',
    }),
    new DraggableElement({
        name: 'item10',
        size: new Vector2(174, 95),
        initialPosition: new Vector2(1300, 728),
        targetPosition: new Vector2(1168, 357),
        layer: PuzzleLayersEnum.LAYER2,
        finalLayer: PuzzleLayersEnum.LAYER2,
        image: 'Augsa_Tresa_Spura.png',
    }),
    new DraggableElement({
        name: 'item11',
        size: new Vector2(216, 92),
        initialPosition: new Vector2(1367, 893),
        targetPosition: new Vector2(918, 317),
        layer: PuzzleLayersEnum.LAYER2,
        finalLayer: PuzzleLayersEnum.LAYER2,
        image: 'Augsa_Videja_Spura.png',
    }),
];